curl http://localhost:8080/albums

###

curl http://localhost:8080/albums/5

###

curl -X "DELETE" http://localhost:8080/albums/4
###

curl -X "PUT" http://localhost:8080/albums/4 \
    --include \
    --header "Content-Type: application/json" \
    --request "POST" \
    --data '{"title": "test"}'

###

curl http://localhost:8080/albums \
    --include \
    --header "Content-Type: application/json" \
    --request "POST" \
    --data '{"id": "5", "title": "The Modern Sound of Betty Carter", "artist": "Betty Carter", "price": 39.99}'